"""Authoring commands: book, paper, part, chapter."""

import re
import sys
from pathlib import Path
from .utils import (
    find_repo_root, find_book_root, find_part_root,
    find_next_number, make_slug, slug_to_title,
    ensure_dir, write_file
)


# Book entry template (for 00_introduction)
BOOK_ENTRY_TEMPLATE = r"""\documentclass{{book}}

\input{{../shared/preamble}}
\input{{../shared/macros}}
\input{{../shared/notation}}
\input{{../shared/identity}}

\title{{{title}}}

\begin{{document}}

\frontmatter
\maketitle
\tableofcontents
\input{{build/sections_index}}

\mainmatter
\input{{build/chapters_index}}

\backmatter
% Bibliography, index, etc.

\end{{document}}
"""

# Empty sections index (no sectioning commands allowed)
SECTIONS_INDEX_TEMPLATE = """% Frontmatter sections index
% This file is generated by tex-repo build

"""

# Empty chapters index (will be populated by build)
CHAPTERS_INDEX_TEMPLATE = """% Chapters index
% This file is generated by tex-repo build
"""

PART_TEX_TEMPLATE = r"""\part{{{title}}}
"""

CHAPTER_TEX_TEMPLATE = r"""\chapter{{{title}}}

% Chapter content goes here
"""

PAPER_ENTRY_TEMPLATE = r"""\documentclass{{article}}

\input{{../shared/preamble}}
\input{{../shared/macros}}
\input{{../shared/notation}}
\input{{../shared/identity}}

\title{{{title}}}

\begin{{document}}

\maketitle

\begin{{abstract}}
Abstract text here.
\end{{abstract}}

\section{{Introduction}}

% Content here

\bibliographystyle{{plain}}
\bibliography{{refs}}

\end{{document}}
"""


def cmd_book(args):
    """
    Create a book-class document.
    
    SPECIAL CASE: book "Introduction" populates 00_introduction/ (must be empty).
    Must be run from repository root.
    """
    # Must be at repo root
    repo_root = find_repo_root()
    if repo_root is None:
        print("Error: Not in a tex-repo repository", file=sys.stderr)
        print("Run 'tex-repo init <name>' first", file=sys.stderr)
        return 1
    
    if Path.cwd() != repo_root:
        print("Error: 'tex-repo book' must be run from repository root", file=sys.stderr)
        print(f"Repository root: {repo_root}", file=sys.stderr)
        return 1
    
    title = args.title
    
    # Special case: "Introduction" uses fixed 00_introduction directory
    if title.strip().lower() == "introduction":
        dir_name = "00_introduction"
        book_dir = repo_root / dir_name
        
        # Check if directory exists and is empty (created by init)
        if book_dir.exists():
            # Must be empty or only have build/ artifacts
            existing_items = [item for item in book_dir.iterdir() 
                            if item.name not in {'build', '.DS_Store'}]
            if existing_items:
                print(f"Error: Directory '00_introduction' already contains files", file=sys.stderr)
                print("It can only be populated once", file=sys.stderr)
                return 1
    else:
        # Other books use numbering
        slug = make_slug(title)
        next_num = find_next_number(repo_root)
        dir_name = f"{next_num}_{slug}"
        book_dir = repo_root / dir_name
        
        if book_dir.exists():
            print(f"Error: Directory '{dir_name}' already exists", file=sys.stderr)
            return 1
    
    # Create/populate book structure
    ensure_dir(book_dir)
    
    # Create parts structure
    ensure_dir(book_dir / 'parts' / 'frontmatter')
    ensure_dir(book_dir / 'parts' / 'parts')
    ensure_dir(book_dir / 'parts' / 'backmatter')
    
    # Create build directory with spine files
    ensure_dir(book_dir / 'build')
    write_file(book_dir / 'build' / 'sections_index.tex', SECTIONS_INDEX_TEMPLATE)
    write_file(book_dir / 'build' / 'chapters_index.tex', CHAPTERS_INDEX_TEMPLATE)
    
    # Create entry .tex file (name matches directory)
    entry_file = book_dir / f"{dir_name}.tex"
    content = BOOK_ENTRY_TEMPLATE.format(title=title)
    write_file(entry_file, content)
    
    return 0


def cmd_paper(args):
    """
    Create an article-class paper at repository root.
    
    Must be run from repository root.
    Auto-numbered with NN_<slug> pattern.
    Slug must be unique (cannot create multiple papers with same slug).
    """
    # Must be at repo root
    repo_root = find_repo_root()
    if repo_root is None:
        print("Error: Not in a tex-repo repository", file=sys.stderr)
        return 1
    
    if Path.cwd() != repo_root:
        print("Error: 'tex-repo paper' must be run from repository root", file=sys.stderr)
        print(f"Repository root: {repo_root}", file=sys.stderr)
        return 1
    
    title = args.title
    slug = make_slug(title)
    
    # Check if slug already exists (any NN_<slug> directory)
    for item in repo_root.iterdir():
        if item.is_dir() and re.match(r'^\d\d_', item.name):
            existing_slug = '_'.join(item.name.split('_')[1:])
            if existing_slug == slug:
                print(f"Error: A paper/book with slug '{slug}' already exists: {item.name}", file=sys.stderr)
                return 1
    
    # Find next number
    next_num = find_next_number(repo_root)
    dir_name = f"{next_num}_{slug}"
    paper_dir = repo_root / dir_name
    
    if paper_dir.exists():
        print(f"Error: Directory '{dir_name}' already exists", file=sys.stderr)
        return 1
    
    # Create paper structure
    ensure_dir(paper_dir)
    ensure_dir(paper_dir / 'sections')
    ensure_dir(paper_dir / 'build')
    
    # Create entry .tex file (name matches directory)
    entry_file = paper_dir / f"{dir_name}.tex"
    entry_content = PAPER_ENTRY_TEMPLATE.format(title=title)
    write_file(entry_file, entry_content)
    
    # Create refs.bib
    write_file(paper_dir / 'refs.bib', '% References\n')
    
    return 0



def cmd_part(args):
    """
    Create a part inside a book.
    
    Must be run inside a book directory.
    Auto-numbered (01_, 02_, ...).
    """
    # Must be inside a book
    book_root = find_book_root()
    if book_root is None:
        print("Error: Not inside a book directory", file=sys.stderr)
        print("Run 'tex-repo part' from inside a book (e.g., 00_introduction/)", file=sys.stderr)
        return 1
    
    title = args.title
    slug = make_slug(title)
    
    # Parts go under parts/parts/
    parts_dir = book_root / 'parts' / 'parts'
    if not parts_dir.exists():
        print(f"Error: {parts_dir} does not exist", file=sys.stderr)
        return 1
    
    # Check if slug already exists
    for item in parts_dir.iterdir():
        if item.is_dir() and re.match(r'^\d\d_', item.name):
            existing_slug = '_'.join(item.name.split('_')[1:])
            if existing_slug == slug:
                print(f"Error: A part with slug '{slug}' already exists: {item.name}", file=sys.stderr)
                return 1
    
    # Find next number (parts start at 01)
    next_num = find_next_number(parts_dir)
    if next_num == "00":
        next_num = "01"
    
    dir_name = f"{next_num}_{slug}"
    part_dir = parts_dir / dir_name
    
    if part_dir.exists():
        print(f"Error: Directory '{dir_name}' already exists", file=sys.stderr)
        return 1
    
    # Create part structure
    ensure_dir(part_dir)
    ensure_dir(part_dir / 'chapters')
    
    # Create part.tex
    part_content = PART_TEX_TEMPLATE.format(title=title)
    write_file(part_dir / 'part.tex', part_content)
    
    return 0


def cmd_chapter(args):
    """
    Create a chapter inside a part.
    
    Must be run inside a part directory.
    Creates chapters/NN_<slug>.tex file (not a directory).
    """
    # Must be inside a part
    part_root = find_part_root()
    if part_root is None:
        print("Error: Not inside a part directory", file=sys.stderr)
        print("Run 'tex-repo chapter' from inside a part (e.g., parts/parts/01_foundations/)", file=sys.stderr)
        return 1
    
    title = args.title
    slug = make_slug(title)
    
    # Chapters go under chapters/
    chapters_dir = part_root / 'chapters'
    if not chapters_dir.exists():
        ensure_dir(chapters_dir)
    
    # Check if slug already exists
    for item in chapters_dir.iterdir():
        if item.is_file() and item.suffix == '.tex' and re.match(r'^\d\d_', item.name):
            existing_slug = item.stem.split('_', 1)[1] if '_' in item.stem else ''
            if existing_slug == slug:
                print(f"Error: A chapter with slug '{slug}' already exists: {item.name}", file=sys.stderr)
                return 1
    
    # Find next number (chapters start at 01)
    next_num = find_next_number(chapters_dir)
    if next_num == "00":
        next_num = "01"
    
    file_name = f"{next_num}_{slug}.tex"
    chapter_file = chapters_dir / file_name
    
    if chapter_file.exists():
        print(f"Error: File '{file_name}' already exists", file=sys.stderr)
        return 1
    
    # Create chapter .tex file
    chapter_content = CHAPTER_TEX_TEMPLATE.format(title=title)
    write_file(chapter_file, chapter_content)
    
    return 0

