"""Installation command for tex-repo environment guides.

EXPLICIT WARNING: This module executes system commands and is intended
for personal use only. It requires explicit user confirmation before
executing any system modification commands.
"""

import os
import platform
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


GUIDE_HEADER_SIGNATURE = "# Generated automatically by tex-repo env guide"


def validate_guide_file(guide_path: Path) -> bool:
    """Validate that the guide file was generated by tex-repo.
    
    Returns:
        True if file is a valid tex-repo generated guide
    """
    if not guide_path.exists():
        print(f"Error: Guide file not found: {guide_path}")
        return False
    
    try:
        with open(guide_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        if GUIDE_HEADER_SIGNATURE not in content:
            print(f"Error: {guide_path} is not a tex-repo generated guide")
            print("Only guides generated by 'tex-repo env guide' are accepted")
            return False
            
        return True
    except Exception as e:
        print(f"Error reading guide file: {e}")
        return False


def extract_commands_from_guide(guide_path: Path) -> List[str]:
    """Extract installation commands from a guide file.
    
    Returns:
        List of shell commands to execute
    """
    commands = []
    current_os = platform.system()
    
    try:
        with open(guide_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        in_code_block = False
        in_relevant_section = False
        
        for line in lines:
            line = line.strip()
            
            # Check for OS-specific sections
            if current_os == 'Linux':
                if '### Ubuntu/Debian Systems' in line:
                    in_relevant_section = True
                elif '### Fedora/RHEL/CentOS Systems' in line:
                    in_relevant_section = True
                elif line.startswith('### ') and 'Systems' in line:
                    in_relevant_section = False
            elif current_os == 'Darwin':  # macOS
                if '### macOS Systems' in line:
                    in_relevant_section = True
                elif line.startswith('### ') and 'Systems' in line:
                    in_relevant_section = False
            
            # Track code blocks
            if line.startswith('```bash'):
                in_code_block = True
                continue
            elif line.startswith('```'):
                in_code_block = False
                continue
            
            # Extract commands from relevant sections
            if in_code_block and in_relevant_section and line:
                # Skip comments
                if line.startswith('#'):
                    continue
                commands.append(line)
    
    except Exception as e:
        print(f"Error parsing guide file: {e}")
        return []
    
    return commands


def check_system_support() -> bool:
    """Check if current system is supported for installation.
    
    Returns:
        True if system is supported
    """
    current_os = platform.system()
    
    if current_os == 'Linux':
        # Check for apt or dnf
        if os.system('which apt >/dev/null 2>&1') == 0:
            return True
        elif os.system('which dnf >/dev/null 2>&1') == 0:
            return True
        else:
            print("Error: Unsupported Linux distribution")
            print("This command supports only apt-based (Ubuntu/Debian) or dnf-based (Fedora/RHEL) systems")
            return False
    elif current_os == 'Darwin':  # macOS
        # Check for brew
        if os.system('which brew >/dev/null 2>&1') == 0:
            return True
        else:
            print("Error: Homebrew not found")
            print("Install Homebrew from: https://brew.sh")
            print("Or manually install MacTeX from: https://tug.org/mactex/")
            return False
    else:
        print(f"Error: Unsupported operating system: {current_os}")
        print("This command supports only Linux (apt/dnf) and macOS (brew)")
        return False


def confirm_execution(commands: List[str]) -> bool:
    """Ask user to confirm command execution.
    
    Returns:
        True if user confirms
    """
    print("This will execute the following system installation commands:")
    print()
    for cmd in commands:
        print(f"  {cmd}")
    print()
    
    print("⚠️  WARNING: These commands will modify your system.")
    print("   - They may require administrator privileges (sudo)")
    print("   - They may download and install large packages") 
    print("   - This action cannot be easily undone")
    print()
    
    response = input("This will execute system installation commands. Continue? [y/N]: ").strip()
    
    return response.lower() == 'y'


def execute_commands(commands: List[str]) -> int:
    """Execute installation commands.
    
    Returns:
        0 if all commands succeed, non-zero on first failure
    """
    for i, cmd in enumerate(commands, 1):
        print(f"\n[{i}/{len(commands)}] Executing: {cmd}")
        print("-" * 50)
        
        try:
            result = subprocess.run(cmd, shell=True, check=False)
            if result.returncode != 0:
                print(f"\n❌ Command failed with exit code {result.returncode}")
                print(f"Failed command: {cmd}")
                return result.returncode
        except KeyboardInterrupt:
            print(f"\n⚠️  Installation interrupted by user")
            return 130
        except Exception as e:
            print(f"\n❌ Error executing command: {e}")
            return 1
    
    print(f"\n✅ All {len(commands)} commands executed successfully!")
    print("\nVerify your installation with: tex-repo env check")
    return 0


def execute_guide(guide_path_str: str) -> int:
    """Execute installation commands from a tex-repo generated guide.
    
    Args:
        guide_path_str: Path to the guide file
        
    Returns:
        0 on success, non-zero on failure
    """
    guide_path = Path(guide_path_str).resolve()
    
    # Validate guide file
    if not validate_guide_file(guide_path):
        return 1
    
    # Check system support
    if not check_system_support():
        return 1
    
    # Extract commands
    commands = extract_commands_from_guide(guide_path)
    if not commands:
        print("No installation commands found in guide for your system")
        print("The guide may not contain instructions for your OS")
        return 1
    
    # Confirm with user
    if not confirm_execution(commands):
        print("Installation cancelled by user")
        return 1
    
    # Execute commands
    return execute_commands(commands)